server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb 
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true




build:
  version: "3.0"

accounts:
  message: "This Is Demo Message for ConfigurationProperties. DEFAULT"
  contactDetails:
    name: "demo-Developer"
    email: "demoaccount@mail.com"
  onCallSupport:
    - 91 001 001 002
    - 91 002 003 004


