server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


build:
  version: 2.0

cards:
  contact:
    name: "dev"
    email: "dev-cards@dev.com"
  message: "This is Cards service using DEV env"
