server:
  port: 8090
  
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: 1.1

loans:
  contact:
    name: "dev"
    email: "dev-loans@dev.com"
  message: "This is Loans service using dev env(Default)."
